# Generated by Django 2.0.7 on 2018-07-25 04:19

from django.db import migrations, models
import django.db.models.deletion
import mysite1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(default=None, upload_to=mysite1.models.ariticleImg)),
                ('test', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=8)),
                ('email', models.CharField(default='', max_length=32)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to='mysite1.User'),
        ),
    ]
