# Generated by Django 2.0.7 on 2018-08-04 15:05

from django.db import migrations, models
import django.db.models.deletion
import mysite1.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('animeid', models.AutoField(primary_key=True, serialize=False)),
                ('seesion', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(default=None, upload_to=mysite1.models.animeImg)),
                ('introduction', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episodeid', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=2000)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_anime', to='mysite1.Anime')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='test',
            field=models.TextField(max_length=2000),
        ),
    ]
