# Generated by Django 2.0.7 on 2018-07-22 09:24

from django.db import migrations, models
import mysite1.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default=None, upload_to=mysite1.models.ariticleImg),
        ),
    ]
