# Generated by Django 2.0.7 on 2018-08-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0004_auto_20180810_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='episode',
            name='num',
            field=models.CharField(max_length=50),
        ),
    ]
